### ISSUE TITLE
O Heroku não localiza o repositório

### ISSUE THREAD

**Issue by 45biceps** [alyssapiresfernandescefet/openrpg#12]
Aparece isso:
Item could not be retrieved:
GET https://api.github.com/search/repositories?q=fork%3Atrue+user%3A45biceps+openrpg: 422 - Validation Failed Error summary: message: The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them. resource: Search field: q code: invalid // See: https://docs.github.com/v3/search/

**Comment by alyssapiresfernandescefet** [comment]
Olá! Vi aqui que você não fez o fork do repositório para a sua conta. Pro Open RPG aparecer na sua da Heroku, você precisa fazer o fork desse repositório original. Seria algo como "espelhar" o meu repositório para a sua conta.

**Comment by 45biceps** [comment]
> Olá! Vi aqui que você não fez o fork do repositório para a sua conta. Pro Open RPG aparecer na sua da Heroku, você precisa fazer o fork desse repositório original. Seria algo como "espelhar" o meu repositório para a sua conta.

como faço isso?
