### ISSUE TITLE
opa

### ISSUE THREAD

**Issue by luiz1238** [alyssapiresfernandescefet/openrpg#2]
mt boa tarde, eu dnv USDUHSAUHD

mas como coloca no obs ? nao entendi direito essa parte

**Comment by alyssapiresfernandescefet** [comment]
Você copia a URL do retrato clicando em "Retrato" no painel do admin e joga no Browser Source do OBS, aí você configura largura e altura e já tá pronto! Atributos e rolagens de dados na tela totalmente automáticos com simples passos.
