### ISSUE TITLE
dados de características

### ISSUE THREAD

**Issue by luiz1238** [alyssapiresfernandescefet/openrpg#4]
eu tava vendo aqui, e nas novas atualizações

as características so tem sucesso (ou as ramificações) e so da fracasso se o resultado for 1

**Comment by alyssapiresfernandescefet** [comment]
Eu achei conveniente que qualquer 1 fosse fracasso, mas agora que você apontou talvez fosse melhor deixar essa decisão pro mestre. Vou fazer essa mudança.

**Comment by alyssapiresfernandescefet** [comment]
Pronto, fiz essa mudança no commit 893d2e7ece0a6a1a466b77fc9b8d7a856d72dfca .

**Comment by luiz1238** [comment]
também acontece de quando atualizar a vida ou sanidade no obs fica so um lado

tipo eu tenho 10/10 de vida

se eu mudar fica 9/

**Comment by luiz1238** [comment]
e pra avisar continua o erro dos dados

acho que seja algum erro de cálculos na parte de características, tipo no que eu to testando aqui eu tenho 10 de força, o sucesso so seria a partir de 11 certo ?

nao é o que acontece, tirando 5 ainda é um sucesso

**Comment by alyssapiresfernandescefet** [comment]
Bug fix do retrato exibindo comportamento estranho nos atributos resolvido em 39b9ca4574f4e310a8ace7788a59d3703d0339f8 .

Bug fix da característica sempre rolando como 20 resolvido em abe6e85687e7692380cecd1bf0e38950742db0df .

Muito obrigada por me ajudar a encontrar bugs!

**Comment by luiz1238** [comment]
AE deu tudo certo

se algo acontecer eu já venho avisar pra vc
